import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fontPrimary = localFont({ src: "/ui/fonts/ClashGrotesk-variable.ttf" });
const fontSecondary = localFont({
  src: "/ui/fonts/Sora-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontPrimary.className} overflow-auto`}>
      <body className="w-screen bg-gradient-to-l from-slate-900 to-portafolio-cuaternario overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}

export { fontPrimary, fontSecondary };
