import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { Inter } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const GTsuper = localFont({
  src: [
    {
      path: "/ui/fonts/GT-Super-Text-Regular-Trial.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/ui/fonts/GT-Super-Text-Bold-Trial.otf",
      weight: "700",
      style: "normal",
    }
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GTsuper.className} overflow-auto snap-y scroll-smooth`}>
      <body className="relative">
        {children}
      </body>
    </html>
  );
}

export { GTsuper, inter };
